### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by shivangibithel** [shirley-wu/text_to_table#6]
Hi @shirley-wu 

Really Nice work!

I am trying to train on the given datasets, but I am getting the following logs and unable to complete the training. Can you please tell me what am I doing wrong here?

I am using python 3.8.8 and other libraries and versions exactly as mentioned in requirement.txt. I have only 4 available GPUs to train, so I changed this CUDA_VISIBLE_DEVICES=0,1,2,3 in the bash script. 

2022-12-08 23:36:17 | INFO | fairseq.distributed_utils | distributed init (rank 0): tcp://localhost:14063
2022-12-08 23:36:17 | INFO | fairseq.distributed_utils | distributed init (rank 1): tcp://localhost:14063
2022-12-08 23:36:17 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 1
2022-12-08 23:36:17 | INFO | fairseq.distributed_utils | distributed init (rank 2): tcp://localhost:14063
2022-12-08 23:36:17 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 2
2022-12-08 23:36:17 | INFO | fairseq.distributed_utils | distributed init (rank 3): tcp://localhost:14063
2022-12-08 23:36:17 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 3
2022-12-08 23:36:17 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 0
2022-12-08 23:36:17 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2022-12-08 23:36:17 | INFO | fairseq.distributed_utils | initialized host Dumbledore as rank 0
2022-12-08 23:36:17 | INFO | torch.distributed.distributed_c10d | Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2022-12-08 23:36:17 | INFO | fairseq.distributed_utils | initialized host Dumbledore as rank 1
2022-12-08 23:36:17 | INFO | torch.distributed.distributed_c10d | Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2022-12-08 23:36:17 | INFO | fairseq.distributed_utils | initialized host Dumbledore as rank 2
2022-12-08 23:36:17 | INFO | torch.distributed.distributed_c10d | Rank 3: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2022-12-08 23:36:17 | INFO | fairseq.distributed_utils | initialized host Dumbledore as rank 3
2022-12-08 23:36:19 | INFO | fairseq_cli.train | Namespace(activation_fn='gelu', adam_betas='(0.9, 0.999)', adam_eps=1e-08, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, all_gather_list_size=16384, arch='bart_base', attention_dropout=0.1, batch_size=None, batch_size_valid=None, best_checkpoint_metric='loss', bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='', clip_norm=0.1, cpu=False, criterion='label_smoothed_cross_entropy', cross_self_attention=False, curriculum=0, data='data/wikibio/bins', data_buffer_size=10, dataset_impl=None, ddp_backend='c10d', decoder_attention_heads=12, decoder_embed_dim=768, decoder_embed_path=None, decoder_ffn_embed_dim=3072, decoder_input_dim=768, decoder_layerdrop=0, decoder_layers=6, decoder_layers_to_keep=None, decoder_learned_pos=True, decoder_normalize_before=False, decoder_output_dim=768, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method='tcp://localhost:14063', distributed_no_spawn=False, distributed_num_procs=4, distributed_port=-1, distributed_rank=0, distributed_world_size=4, distributed_wrapper='DDP', dropout=0.1, empty_cache_freq=0, encoder_attention_heads=12, encoder_embed_dim=768, encoder_embed_path=None, encoder_ffn_embed_dim=3072, encoder_layerdrop=0, encoder_layers=6, encoder_layers_to_keep=None, encoder_learned_pos=True, encoder_normalize_before=False, eval_bleu=False, eval_bleu_args=None, eval_bleu_detok='space', eval_bleu_detok_args=None, eval_bleu_print_samples=False, eval_bleu_remove_bpe=None, eval_tokenized_bleu=False, fast_stat_sync=False, find_unused_parameters=True, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, fp16=True, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='test', ignore_prefix_size=0, keep_best_checkpoints=3, keep_interval_updates=-1, keep_last_epochs=-1, label_smoothing=0.1, layernorm_embedding=True, left_pad_source='True', left_pad_target='False', load_alignments=False, localsgd_frequency=3, log_format=None, log_interval=100, lr=[0.0001], lr_scheduler='inverse_sqrt', max_epoch=0, max_source_positions=1024, max_target_positions=1024, max_tokens=4096, max_tokens_valid=4096, max_update=40000, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1.0, model_parallel_size=1, no_cross_attention=False, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_scale_embedding=True, no_seed_provided=False, no_token_positional_embeddings=False, nprocs_per_node=4, num_batch_buckets=0, num_shards=1, num_workers=16, optimizer='adam', optimizer_overrides='{}', patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, pooler_activation_fn='tanh', pooler_dropout=0.0, profile=False, quant_noise_pq=0, quant_noise_pq_block_size=8, quant_noise_scalar=0, quantization_config_path=None, relu_dropout=0.0, report_accuracy=False, required_batch_size_multiple=1, required_seq_len_multiple=1, reset_dataloader=True, reset_lr_scheduler=False, reset_meters=True, reset_optimizer=True, restore_file='bart.base//model.pt', save_dir='checkpoints', save_interval=1, save_interval_updates=0, scoring='bleu', seed=1, sentence_avg=False, shard_id=0, share_all_embeddings=True, share_decoder_input_output_embed=True, skip_invalid_size_inputs_valid_test=True, slowmo_algorithm='LocalSGD', slowmo_momentum=None, source_lang='text', stop_time_hours=0, target_lang='data', task='translation', tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', truncate_source=True, update_freq=[1], upsample_primary=1, use_bmuf=False, use_old_adam=False, user_dir=None, valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, warmup_init_lr=1e-07, warmup_updates=4000, weight_decay=0.01, zero_sharding='none')
Traceback (most recent call last):
  File "custom_train.py", line 463, in <module>
    cli_main()
  File "custom_train.py", line 459, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 283, in call_main
    torch.multiprocessing.spawn(
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 270, in distributed_main
    main(args, **kwargs)
  File "/DATA/shivangib/Huawei_improvement/text_to_table/custom_train.py", line 168, in main
    task = tasks.setup_task(args)
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/fairseq/tasks/__init__.py", line 28, in setup_task
    return TASK_REGISTRY[task_cfg.task].setup_task(task_cfg, **kwargs)
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/fairseq/tasks/translation.py", line 266, in setup_task
    src_dict = cls.load_dictionary(
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/fairseq/tasks/fairseq_task.py", line 54, in load_dictionary
    return Dictionary.load(filename)
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/fairseq/data/dictionary.py", line 214, in load
    d.add_from_file(f)
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/fairseq/data/dictionary.py", line 227, in add_from_file
    raise fnfe
  File "/home/shivangib/miniconda3/envs/text2table/lib/python3.8/site-packages/fairseq/data/dictionary.py", line 224, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'data/wikibio/bins/dict.text.txt'

**Comment by shirley-wu** [comment]
Hi, it seems you do not have a necessary file `data/wikibio/bins/dict.text.txt`. The directory `data/wikibio/bins/` should contain `dict.{data,text}.txt` and `{train,valid,test}.text-data.{data,text}.{bin,idx}`.

Have you setup the data directory like following the instruction at https://github.com/shirley-wu/text_to_table#dataset ? Basically you need to (1) download and unzip the data from [Google Drive](https://drive.google.com/file/d/1zTfDFCl1nf_giX7IniY5WbXi9tAuEHDn/view?usp=sharing), (2) download bart-base model from https://github.com/facebookresearch/fairseq/tree/main/examples/bart and unzip at `bart.base/`, and (3) preprocess the dataset by running `bash scripts/preprocess.sh data/wikibio/ bart.base/`. Then you should have all the necessary files under `data/wikibio/bins/`.

Please let me know if you meet any more problems.

**Comment by shivangibithel** [comment]
Hi @shirley-wu 

Thanks for replying.
I am able to train the model now, but while testing the model using the given inference command I am getting zero values as result. (in the screenshot) Please help me figure out the issue here.

![image](https://user-images.githubusercontent.com/19774925/206862870-128c2b71-8e1e-4648-aaee-552af3ed2d49.png)


Thanks

**Comment by shirley-wu** [comment]
There is no way to tell why the numbers are zero from the information so far. From the filenames (`checkpoint50.best_2.2620.pt` etc) it seems the best checkpoints can achieve ~2.26 loss. This matches my own experiements, so the model should be well-trained. A few stuff you may try:
* Can you confirm you trained the model on WikiTableText?
* Have you ever conducted multiple training process? Such as you first train on one dataset, and then on another? If so, since the different scripts all save models to `checkpoints/`, this may cause some issue.
* Can you try `test_vanilla.sh` and see if the numbers are still low?
* Can you post `checkpoints/log` and a few lines of the generation outputs (`checkpoints/checkpoint_average_best-3.pt.test_constrained.out.text`) here?
